name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create destination directory
        run: |
          gcloud compute ssh my-webserver --zone=us-central1-a --command="sudo mkdir -p /var/www/html && sudo chmod 777 /var/www/html"

      - name: Deploy to Compute Engine
        run: |
          gcloud compute scp --zone="us-central1-a" --recurse ./* my-webserver:/var/www/html/
