name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to VM Instance
        run: |
          # Create a directory if it doesn't exist
          gcloud compute ssh ${{ secrets.VM_NAME }} --zone=${{ secrets.ZONE }} \
            --command="sudo mkdir -p /var/www/html && sudo chown -R \$USER:\$USER /var/www/html"

          # Copy files to the instance
          gcloud compute scp --zone=${{ secrets.ZONE }} --recurse ./* ${{ secrets.VM_NAME }}:/var/www/html/

          # Set proper permissions and restart Apache
          gcloud compute ssh ${{ secrets.VM_NAME }} --zone=${{ secrets.ZONE }} \
            --command="sudo chown -R www-data:www-data /var/www/html/ && sudo systemctl restart apache2"
